# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#

templates:
  params:
    author-name: Michael Schaper
    author-email: michael.schaper@uibk.ac.at
    category: Logic
    copyright: 'Copyright: (c) 2018 Michael Schaper'
    github-username: mischel
  scm-init: git

